title: X Î±
description: Awesome things about sci-surf.
show_downloads: true
google_analytics:
remote_theme: pages-themes/merlot@v0.2.0
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one
